In [3]:
import numpy as np


In [4]:
l1=[1,2,3,4]
n1=np.array(l1)
n1

array([1, 2, 3, 4])

In [5]:
type(n1)

numpy.ndarray

In [6]:
n2=np.array([[1,2,3,4],[4,3,2,1]])
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [7]:
type(n2)

numpy.ndarray

In [8]:
#intialize a empty array
n3=np.zeros((2,3))
n3


array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
type(n3)

numpy.ndarray

In [10]:
n4=np.zeros((10,10))
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
#intilize numpy array with same number
n5=np.full((3,3),10)
n5

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [12]:
type(n5)

numpy.ndarray

In [13]:
#intialzing python 
n6=np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
n6=np.arange(10,1000,10)
n6



array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390,
       400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520,
       530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650,
       660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780,
       790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910,
       920, 930, 940, 950, 960, 970, 980, 990])

In [15]:
#intialze numpy random input

In [16]:
n7=np.random.randint(10,100,10)
n7

array([92, 35, 76, 91, 36, 64, 23, 87, 48, 70])

In [17]:
#shape of numpy array

In [19]:
n8=np.array([[1,5,8,5],[8,95,45,2]])
n8.shape

(2, 4)